server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/finalprojectweb"
    username: MyDung
    password: "Mydung@1012"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
